/**
 * Stamp public/sw.js with a cache name derived from model file contents.
 * Any change to public/models/teman-kopi/* bumps the SW cache automatically
 * on the next `npm run build` (no manual v2 → v3 edits).
 */
import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const MODEL_DIR = path.join(ROOT, 'public/models/teman-kopi')
const SW_OUT = path.join(ROOT, 'public/sw.js')

const SHELL_ASSETS = [
  '/',
  '/index.html',
  '/manifest.webmanifest',
  '/favicon.svg',
]

async function hashModelFiles() {
  const names = (await readdir(MODEL_DIR))
    .filter((n) => !n.startsWith('.'))
    .sort()

  if (names.length === 0) {
    throw new Error(`No model files in ${MODEL_DIR}`)
  }

  const hash = createHash('sha256')
  const modelUrls = []

  for (const name of names) {
    const abs = path.join(MODEL_DIR, name)
    const buf = await readFile(abs)
    hash.update(name)
    hash.update('\0')
    hash.update(buf)
    modelUrls.push(`/models/teman-kopi/${name}`)
  }

  return {
    shortHash: hash.digest('hex').slice(0, 12),
    modelUrls,
    names,
  }
}

function renderSw(cacheName, precacheUrls) {
  const list = precacheUrls.map((u) => `          '${u}',`).join('\n')
  return `/* Teman Kopi offline service worker — generated by scripts/stamp-sw.mjs; do not edit by hand */
const CACHE = '${cacheName}'

self.addEventListener('install', (event) => {
  self.skipWaiting()
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      cache
        .addAll([
${list}
        ])
        .catch(() => undefined),
    ),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const cached = await cache.match(request)
      if (cached) return cached
      try {
        const fresh = await fetch(request)
        if (fresh && fresh.ok) {
          cache.put(request, fresh.clone())
        }
        return fresh
      } catch {
        if (request.mode === 'navigate') {
          const fallback = await cache.match('/index.html')
          if (fallback) return fallback
        }
        return new Response('Offline', { status: 503, statusText: 'Offline' })
      }
    }),
  )
})
`
}

async function main() {
  const { shortHash, modelUrls, names } = await hashModelFiles()
  const cacheName = `teman-kopi-${shortHash}`
  const precacheUrls = [...SHELL_ASSETS, ...modelUrls]
  await writeFile(SW_OUT, renderSw(cacheName, precacheUrls), 'utf8')
  console.log(`Stamped ${path.relative(ROOT, SW_OUT)}`)
  console.log(`  CACHE=${cacheName}`)
  console.log(`  model files: ${names.join(', ')}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
